export {default as ControlPanel} from "@/views/map-view/ControlPanel"
export {default as Map} from "@/views/map-view/Map"
export {default as Industries} from "@/views/map-view/Industries"
export {default as Location} from "@/views/map-view/Location"
export {default as Grades} from "@/views/map-view/Grades"
export {default as Facilities} from "@/views/map-view/Facilities"
export {default as AdditionalServices} from "@/views/map-view/AdditionalServices"