import type { Metadata } from "next";
import "@/css/global.css";
import { inter, playfair } from "@/assets/fonts";
import { Navigation } from "@/layout/navigation";
import { Footer } from "@/layout/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl-PL"
      className={`${inter.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
