export {default as CartIcon} from "@/svgr/CartIcon"
export {default as FiltersIcon} from "@/svgr/FiltersIcon"
export {default as LocationIcon} from "@/svgr/LocationIcon"
export {default as NetworkIcon} from "@/svgr/NetworkIcon"
export {default as StarIcon} from "@/svgr/StarIcon"